### ISSUE TITLE
Missing source code at provided link

### ISSUE THREAD

**Issue by solsen-tl** [apostrophecms/a3-demo#95]
A link from my demo app home page took me to:

https://github.com/apostrophecms/a3-demo/tree/content/modules/github-prs-widget

Which doesn't exist (anymore?).

**Comment by abea** [comment]
Thanks for letting us know. We need to update that link to point to the main branch.

**Comment by abea** [comment]
All fixed. Thanks. @solsen-tl. New demo sites will get the fixed link.

**Comment by abea** [comment]
(It goes to https://github.com/apostrophecms/a3-demo/tree/main/modules/github-prs-widget)
